import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from "next/font/google";
import { Header } from "./components/Header/Header";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Template',
  description: 'Generated by create next app',
  manifest: '/manifest.json'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={`${inter.className}`}>
        <Header />

        {children}

        </body>
    </html>
  )
}
